# Generated by Django 4.0.5 on 2022-07-04 20:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=16, validators=[django.core.validators.RegexValidator(message='Phone number must be entered in the format: 9999999999. Up to 15 digits allowed.', regex='\\d{8,15}$')])),
                ('client_member_id', models.IntegerField()),
                ('account_id', models.IntegerField()),
            ],
        ),
    ]
