#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

python /app/manage.py collectstatic --noinput
python manage.py makemigrations
python /app/manage.py migrate

gunicorn healthcare.wsgi:application --bind 0.0.0.0:8000